name: Build & Test - Hosted

on: [push]

jobs:
  build_and_test:
    name: Build & Test - Hosted
    strategy:
      matrix:
        # we only run on nightly, since leptos needs it 
        rust: [nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: wasm32-unknown-unknown
      - name: Update Dependencies
        run: sudo apt update && sudo apt install pkg-config libssl-dev
      - name: Install Cargo-Leptos
        run: cargo install cargo-leptos
      - uses: actions-rs/cargo@v1
        name: Build Library
        with:
          command: leptos
          args: build --release
      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test
          args: --workspace --release --all-features
